# Generated by Django 5.2.4 on 2025-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='address',
            new_name='deliver_address',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='city',
            new_name='deliver_city',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='state',
            new_name='deliver_state',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='zipcode',
            new_name='deliver_zipcode',
        ),
    ]
